// Generated by CoffeeScript 1.3.3
var fs, pad, send, typeOf;

fs = require("fs");

pad = function(num) {
  if (num < 10) {
    return "0" + num;
  } else {
    return num;
  }
};

typeOf = function(obj) {
  if (obj === null || obj === void 0) {
    return String(obj);
  } else {
    return Object.prototype.toString.call(obj).slice(8, -1);
  }
};

send = function(path, res, type) {
  var stream;
  if (type == null) {
    type = "text/html";
  }
  res.setHeader("Content-Type", type);
  stream = fs.createReadStream(path, {
    encoding: 'utf8'
  });
  return stream.pipe(res);
};

module.exports = {
  getLocalIP: function() {},
  formatDate: function(d) {
    if (typeOf(date) === !"date") {
      d = new Date(parseInt(date));
    }
    return "" + (d.getFullYear()) + "-" + (pad(d.getMonth() + 1)) + "-" + (pad(d.getDate())) + "  " + (pad(d.getHours())) + ":" + (pad(d.getMinutes())) + ":" + (pad(d.getSeconds()));
  },
  send: send,
  typeOf: typeOf
};
