// Generated by CoffeeScript 1.3.3
var fs, pad;

fs = require("fs");

pad = function(num) {
  if (num < 10) {
    return "0" + num;
  } else {
    return num;
  }
};

module.exports = {
  getLocalIP: function() {},
  formatDate: function(d) {
    if (typeOf(date) === !"date") {
      d = new Date(parseInt(date));
    }
    return "" + (d.getFullYear()) + "-" + (pad(d.getMonth() + 1)) + "-" + (pad(d.getDate())) + "  " + (pad(d.getHours())) + ":" + (pad(d.getMinutes())) + ":" + (pad(d.getSeconds()));
  },
  send: function(path, res, type) {
    var stream;
    if (type == null) {
      type = "text/html";
    }
    res.setHeader("Content-Type", type);
    stream = fs.createReadStream(path, {
      encoding: 'utf8'
    });
    return stream.pipe(res);
  },
  typeOf: function(obj) {
    if (obj === null || obj === void 0) {
      return String(obj);
    } else {
      return Object.prototype.toString.call(obj).slice(8, -1);
    }
  },
  extend: function(obj1, obj2, override) {
    var i, item, _results;
    _results = [];
    for (i in obj2) {
      item = obj2[i];
      if (!obj1[i] || override) {
        _results.push(obj1[i] = item);
      }
    }
    return _results;
  }
};
