// Generated by CoffeeScript 1.4.0
(function() {
  var helper, util;

  module.exports = helper = {
    colorify: require("./colorify"),
    Parser: require("./parser")
  };

  util = require("./util");

  util.extend(helper, util);

}).call(this);
