// Generated by CoffeeScript 1.3.3
var Level, colorify, createLogger, log, type, util,
  __slice = [].slice;

colorify = require("./colorify");

util = require("./util");

Level = {
  error: "red",
  warn: "yellow",
  done: "green",
  info: "blue",
  debug: "brightBlack"
};

createLogger = function(type) {
  var color, logFn, suffix;
  logFn = console[type] || console.log;
  color = Level[type];
  suffix = color != null ? colorify(type.toUpperCase(), color) : "";
  return log[type] = function() {
    var dateInfo, msg, now;
    msg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    now = util.formatDate(new Date);
    dateInfo = colorify(now, "cyan");
    return logFn.apply(null, ["" + suffix + "\t " + dateInfo + ":"].concat(__slice.call(msg)));
  };
};

module.exports = log = {
  log: function() {
    var msg, type;
    type = arguments[0], msg = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return log[type].apply(log, msg);
  }
};

for (type in Level) {
  createLogger(type);
}
