// Generated by CoffeeScript 1.3.3
var extend, os;

os = require('os');

extend = function(o1, o2, override) {
  var i, o, _results;
  _results = [];
  for (i in o2) {
    o = o2[i];
    if (!o1[i] || override) {
      _results.push(o1[i] = o);
    }
  }
  return _results;
};

module.exports = {
  extend: function(o1, o2, override) {
    var i, o, _results;
    _results = [];
    for (i in o2) {
      o = o2[i];
      if (!o1[i] || override) {
        _results.push(o1[i] = o);
      }
    }
    return _results;
  },
  getLocalIP: function() {
    var i, inf, item, netInterfaces, results, _i, _len;
    netInterfaces = os.networkInterfaces();
    results = [];
    for (i in netInterfaces) {
      inf = netInterfaces[i];
      for (_i = 0, _len = inf.length; _i < _len; _i++) {
        item = inf[_i];
        if (item.family === "IPv4" && !item.internal) {
          results.push("" + i + " : " + item.address);
        }
      }
    }
    return results;
  },
  formatDate: function(date) {
    var index, str;
    date || (date = Date.now());
    str = date.toString();
    index = str.indexOf("GMT");
    return str.slice(0, index - 1);
  }
};
